Improve limeobject decorator
Lundalogik/lime-web-components pull request #247
Opened 2020-10-23 15:53 UTC by Befkadu1

2020-10-26 08:38 UTC, adrianschmidt commented on packages/decorators/src/state/limeobjects.ts
> +    limetype?: string | ((component?: LimeWebComponent) => string);
`((component?: LimeWebComponent) => string)`

This part means that you can set the value of `limetype` to be a function that optionally takes a `LimeWebComponent` and returns a `string`, right?

I think this might be a breaking change, because if the implementation only accepts a `string`, it doesn't implement this interface correctly.

One way to test would be to locally install this in lime-webclient master, and run a production build (`npm run build`). Presuming this interface is used in lime-webclient, the build should fail if this change is breaking.

2020-10-26 09:12 UTC, adrianschmidt commented on packages/decorators/src/state/limeobjects.ts
> +    limetype?: string | ((component?: LimeWebComponent) => string);
Just tried it, and I get this 😞

![image](https://user-images.githubusercontent.com/154725/97153933-90072f80-1773-11eb-887f-77d2af75f824.png)

```
ERROR in src/app/services-module/state/limeobjects.service.ts:85:27 - error TS2345: Argument of type 'string | ((component?: LimeWebComponent) => string)' is not assignable to parameter of type 'string'.
  Type '(component?: LimeWebComponent) => string' is not assignable to type 'string'.

85             selector.push(options.limetype);
                             ~~~~~~~~~~~~~~~~
```

2020-10-26 09:35 UTC, Befkadu1 commented on packages/decorators/src/state/limeobjects.ts
> +    limetype?: string | ((component?: LimeWebComponent) => string);
Yea haha, I have not pushed the latest one

2020-10-26 09:39 UTC, Befkadu1 commented on packages/decorators/src/state/limeobjects.ts
> +    limetype?: string | ((component?: LimeWebComponent) => string);
As @jensgustafsson said in the meeting, just wait a little bit and make the PRs and you will test all same time

2020-10-26 09:43 UTC, Befkadu1 commented on packages/decorators/src/state/limeobjects.ts
> +    limetype?: string | ((component?: LimeWebComponent) => string);
But if you are eager to test, this are one of the few lines in my the implementation 

<img width="737" alt="Screenshot 2020-10-26 at 10 42 17" src="https://user-images.githubusercontent.com/22968497/97157197-13c31b00-1778-11eb-8cbf-e608630e0237.png">

2020-10-26 10:01 UTC, adrianschmidt commented on packages/decorators/src/state/limeobjects.ts
> +    limetype?: string | ((component?: LimeWebComponent) => string);
I think you misunderstand. I'm not complaining about it not working, I'm saying this is a breaking change in `lime-web-components`, which means we need this to create a new major version, not just a minor version. And when we do that, I think @jgroth has some other stuff we'd like to get merged at the same time, so we don't have to create several new major versions 🙂

2020-10-26 10:04 UTC, Befkadu1 commented on packages/decorators/src/state/limeobjects.ts
> +    limetype?: string | ((component?: LimeWebComponent) => string);
> I think you misunderstand. I'm not complaining about it not working, I'm saying this is a breaking change in `lime-web-components`, which means we need this to create a new major version, not just a minor version. And when we do that, I think @jgroth has some other stuff we'd like to get merged at the same time, so we don't have to create several new major versions 🙂

Aha ok. I talked to @jgroth already, I will contact him when I am ready to do other PRs. Thanks

2020-10-26 10:05 UTC, adrianschmidt commented on packages/decorators/src/state/limeobjects.ts
> +    limetype?: string | ((component?: LimeWebComponent) => string);
"Breaking change" doesn't mean that it's broken, it just means that the client implementing the interface will have to be updated to work with the new version, because *otherwise* it would be broken 🙂

2020-10-26 10:09 UTC, adrianschmidt commented on packages/decorators/src/state/limeobjects.ts
> +    limetype?: string | ((component?: LimeWebComponent) => string);
Note that the commit message for this commit (feat(decorators): improve Limeobjects decorator) must be updated before this is merged. It needs to include `BREAKING CHANGE: <description on change>`, or semantic-release will release a new minor version instead of a new major version.

2020-10-26 14:01 UTC, Befkadu1 commented on packages/decorators/src/state/limeobjects.ts
> +    limetype?: string | ((component?: LimeWebComponent) => string);
> Note that the commit message for this commit (feat(decorators): improve Limeobjects decorator) must be updated before this is merged. It needs to include `BREAKING CHANGE: <description of change>`, or semantic-release will release a new minor version instead of a new major version.

Now it is not a breaking change anymore.

2020-10-26 14:22 UTC, jgroth commented on packages/interfaces/src/service/state-service.interface.ts
> +     * A component to filter any changes to the state by related limetype.
This is way too specific :slightly_smiling_face: Something like this would be better I think
```suggestion
     * The component that is subscribing to the state changes
```

2020-10-26 14:22 UTC, jgroth commented on packages/interfaces/src/service/state-service.interface.ts
> +    component?: any;
```suggestion
    component?: LimeWebComponent;
```

2020-10-26 14:24 UTC, jgroth commented on packages/decorators/src/state/limeobjects.ts
> +    getLimetype?: (component: LimeWebComponent) => string;
We should add some documentation here describing what this method does

2020-10-27 07:47 UTC, jgroth commented on packages/interfaces/src/service/state-service.interface.ts
> +    component?: LimeWebComponent;
It does not feel 100% right to add this to the interface, I'm not sure it really belongs here :thinking: 
We should investigate if we can implement this feature without adding the component to an interface that handles options

2020-10-27 09:23 UTC, adrianschmidt commented on packages/decorators/src/state/limeobjects.ts
> +    limetype?: string | ((component?: LimeWebComponent) => string);
Nice! 👍

2020-10-29 07:39 UTC, Befkadu1 commented on packages/interfaces/src/service/state-service.interface.ts
> +    component?: LimeWebComponent;
component is removed

2020-10-30 10:27 UTC, jensgustafsson requested changes

2020-10-30 11:01 UTC, jgroth commented on packages/decorators/src/factory.ts
> +    ) => StateOptions;
We can type this as `type OptionFactory = (options: LimeobjectsOptions, component: LimeWebComponent) => StateOptions` to make it easier to reuse

2020-10-30 11:10 UTC, jensgustafsson commented on packages/decorators/src/factory.ts
> +    ) => StateOptions;
What would be the difference? **Just curious** 😽

2020-10-30 11:14 UTC, jgroth commented on packages/decorators/src/factory.ts
> +    ) => StateOptions;
We are hardcoding it now in two places, so it's to avoid duplicated code :slightly_smiling_face:

2020-10-30 11:15 UTC, Befkadu1 commented on packages/decorators/src/factory.ts
> +    ) => StateOptions;
> What would be the difference? **Just curious** 😽

Removes duplicates

2020-10-30 11:56 UTC, jensgustafsson approved these changes

2020-10-30 12:55 UTC, merged