feat(decorators): add decorator for accessing user data
Lundalogik/lime-web-components pull request #294
Opened 2021-09-22 12:45 UTC by jgroth

fix Lundalogik/hack-tuesday#190

2021-09-22 12:53 UTC, adrianschmidt commented on packages/decorators/src/state/user-data.ts
> +export function UserData(options: UserDataOptions) {
Is `options` optional? It doesn't look like it since there's no default value, but maybe it still is? I'm just asking since the only property, `options.name`, is optional, so it would make sense if the object is optional too…

2021-09-22 12:55 UTC, jgroth commented on packages/decorators/src/state/user-data.ts
> +export function UserData(options: UserDataOptions) {
No it's not from the way it is declared right now, but maybe it should be :slightly_smiling_face:

2021-09-22 12:55 UTC, adrianschmidt commented on packages/decorators/src/state/user-data.ts
> +    name?: string;
This is the key for the data, right? I think `key` would make it less ambiguous what this is.

Also, we could add a docblock for the property too… 🙂

2021-09-22 12:57 UTC, jgroth commented on packages/decorators/src/state/user-data.ts
> +    name?: string;
Yeah `key` might make more sense here, and we should probably add the docblock as well :+1:

2021-09-22 12:58 UTC, adrianschmidt commented on packages/decorators/src/state/user-data.ts
> +export function UserData(options: UserDataOptions) {
Yeah, if no part of the config is actually required, it would make sense to be able to write:

```
@UserData()
@State()
private userData;
```

Rather than:

```
@UserData({})
@State()
private userData;
```

2021-09-23 12:39 UTC, adrianschmidt approved these changes

2021-09-24 07:47 UTC, adrianschmidt requested changes
Just to prevent this getting merged before we're done with the other necessary PRs.

2021-09-28 06:05 UTC, jgroth commented
Lundalogik/lime-core#984 has been merged so I think we should be able to merge this one as well now :slightly_smiling_face:

2021-09-28 08:32 UTC, adrianschmidt approved these changes

2021-09-28 08:32 UTC, adrianschmidt requested changes
Wait, is this breaking?

2021-09-28 08:33 UTC, jgroth commented
> Wait, is this breaking?

Hmm no it should not be, there is just new stuff added :thinking:

2021-09-28 08:35 UTC, adrianschmidt approved these changes
No, we're just adding a decorator, so not breaking, I was just confused 😅

2021-09-28 08:36 UTC, merged