feat(create-dialog-command): add optional context property
Lundalogik/lime-web-components pull request #302
Opened 2021-10-13 15:36 UTC by FredrikWallstrom

2021-10-15 09:43 UTC, jgroth requested changes

2021-10-15 09:43 UTC, jgroth commented on packages/commands/src/limeobject/create-dialog.command.ts
> +    public context?: string;
This should not be a string, right? 
```suggestion
    public context?: LimeWebComponentContext;
```

2021-10-18 05:39 UTC, FredrikWallstrom commented on packages/commands/src/limeobject/create-dialog.command.ts
> +    public context?: string;
😮  Great catch!

2021-10-18 06:19 UTC, jgroth approved these changes

2021-10-18 06:32 UTC, merged