Refactor decorators
Lundalogik/lime-web-components pull request #381
Opened 2022-03-23 13:58 UTC by jgroth

This deprecates all code in the `decorators` package and moves it to the `lime-web-components` package. GitHub does not give a good preview of the changes here, but I followed the same pattern as in #377 

1. One commit that moves the file to the new location
2. A new commit that fixes any broken imports, documentation, and naming issues. Old decorator is deprecated and re-exports the moved code under the old name.

The most notable change in this PR is a new naming convention for the decorators. Previously we had issues with name collision between types from `interfaces` and `decorators`, e.g. we both had a type and a decorator named `Session` so it was difficult to do something like the following without re-naming the types in your own code.

```ts
class MyComponent {
    @State()
    @Session() // The session decorator
    private session: Session; // The type for the session (name collision)
}    
```

With this PR all decorators are now named `Select...`, e.g. `@SelectSession()` and `@SelectCurrentLimeType()`. This was taken from Redux which has the selector concept[^1] of selecting data from the redux store. The `NgRedux` package that we have used in the webclient also has something similar with the generic `@Select` decorator that allows you to select anything from the state so I think this naming convention makes sense.

[^1]: https://redux.js.org/usage/deriving-data-selectors

2022-03-25 13:57 UTC, adrianschmidt requested changes
Two tiny things, otherwise it looks great 👍

2022-03-25 13:57 UTC, adrianschmidt commented on packages/lime-web-components/src/core/application.ts
> +): PropertyDecorator {
Looks like this change belongs in the preceding commit?

2022-03-25 13:57 UTC, adrianschmidt commented on packages/decorators/src/index.ts
>  export * from './state/limetypes';
Same thing here as in #377, regarding the commit messages, and making sure the changes appear in the changelog.

2022-03-28 11:25 UTC, jgroth commented on packages/lime-web-components/src/core/application.ts
> +): PropertyDecorator {
It took a few tries but I think I managed to sort it out :smile:

2022-03-28 11:25 UTC, jgroth commented on packages/decorators/src/index.ts
>  export * from './state/limetypes';
Fixed :slightly_smiling_face:

2022-03-28 13:18 UTC, adrianschmidt approved these changes
Looks good to me 👍

2022-03-28 13:18 UTC, merged