Fix breaking changes
Lundalogik/lime-web-components pull request #466
Opened 2022-07-05 13:21 UTC by jgroth

This fixes a few unintentional breaking changes and also fixes an issue with module augmentation in the new package

fix Lundalogik/crm-feature#2886

2022-07-05 13:24 UTC, jgroth commented on packages/lime-web-components/src/core/platform.ts
> +export interface PlatformServiceNameType {
Not sure if I'm particularly happy with this name... suggestions are more than welcome :smile:

2022-07-05 13:35 UTC, adrianschmidt commented on packages/lime-web-components/src/core/platform.ts
> +export interface PlatformServiceNameType {
What's the reason for this name change to begin with? 😊

2022-07-05 13:39 UTC, jgroth commented on packages/lime-web-components/src/core/platform.ts
> +export interface PlatformServiceNameType {
Using the same name for both the type and the value caused some problems. It's allowed to have it like that, but I got some weird errors in another repo when trying to define a service on the platform e.g.
```
import { PlatformServiceName } from '@limetech/lime-web-components';
import { HackDemoService } from './service';

const SERVICE_NAME = 'demo';

PlatformServiceName.Demo = SERVICE_NAME;

declare module '@limetech/lime-web-components' {
    interface LimeWebComponentPlatform {
        get(name: PlatformServiceName['Demo']): HackDemoService;
    }

    interface PlatformServiceName {
        /**
         * @see {@link HackDemoService}
         */
        Demo: typeof SERVICE_NAME;
    }
}
```

2022-07-05 13:40 UTC, jgroth commented on packages/lime-web-components/src/core/platform.ts
> +export interface PlatformServiceNameType {
Did not get the same errors when using the same approach in this repo :smile:

2022-07-05 13:45 UTC, adrianschmidt commented on packages/lime-web-components/src/core/platform.ts
> +export interface PlatformServiceNameType {
Ah, I suspected it might be a name conflict. I think that if `PlatformServiceName` is a good name for the property, and this is the type of that property, then `[WhateverThePropertyIsCalled]Type` isn't that bad a name… 😄

2022-07-06 09:10 UTC, adrianschmidt commented on packages/lime-web-components/src/commandbus/types.ts
>  PlatformServiceName.CommandBus = SERVICE_NAME;
I've done the following:

1. Built this branch
2. Installed the old packages from this branch in limeclient.js and built (no errors)
3. Installed the old packages from this branch in lime-crm-components and built (no errors)
4. Installed my local limeclient.js, lime-crm-components, and the old packages from this branch in lime-webclient/frontend/webclient and built, and I'm getting the following error:

<img width="1440" alt="Property 'getHandler' is optional in type 'CommandBusService' but required in type 'CommandBusService'." src="https://user-images.githubusercontent.com/154725/177514284-61fce4cb-820e-42f2-9c18-b980efe08303.png">

(By "old packages", I mean `lime-web-components/packages/commands/`, `lime-web-components/packages/decorators/`, `lime-web-components/packages/interfaces/`, and `lime-web-components/packages/testing/`.)

2022-07-06 09:11 UTC, adrianschmidt commented on packages/lime-web-components/src/commandbus/types.ts
>  PlatformServiceName.CommandBus = SERVICE_NAME;
I thought this was already fixed though? Or was that a similar but distinct error? 🤔

2022-07-06 09:15 UTC, adrianschmidt commented on packages/commands/src/limeobject/save-object.command.ts
>      Command,
Installed and built in `lime-webclient/frontend/admin/` with no errors! 🎉

2022-07-06 09:47 UTC, jgroth commented on packages/lime-web-components/src/commandbus/types.ts
>  PlatformServiceName.CommandBus = SERVICE_NAME;
I think this 0f53042 should fix it

2022-07-06 10:03 UTC, adrianschmidt commented on packages/lime-web-components/src/commandbus/types.ts
>  PlatformServiceName.CommandBus = SERVICE_NAME;
Yes! Fixed it! And now it built with no further errors 👍

2022-07-06 10:10 UTC, adrianschmidt commented on packages/commands/src/limeobject/save-object.command.ts
>      Command,
In `addon-infotiles` I get the following error:

<img width="951" alt="TypeScript: ./src/components/infotiles-loader/infotiles-loader.tsx:17:14 Class 'Loader' incorrectly implements interface 'LimePluginLoader'.Type 'Loader' is missing the following properties from type 'LimePluginLoader': connectedCallback, componentWillUpdate, disconnectedCallback" src="https://user-images.githubusercontent.com/154725/177526414-49fde0d3-81fc-423a-b418-fbf105768df2.png">

I get almost but not quite the same error when using `@limetech/lime-web-components@latest`:

<img width="710" alt="TypeScript: ./src/components/infotiles-loader/infotiles-loader.tsx:17:14 Class 'Loader' incorrectly implements interface 'LimePluginLoader'.Property 'componentWillUpdate' is missing in type 'Loader' but required in type 'LimePluginLoader'." src="https://user-images.githubusercontent.com/154725/177526537-48573ecb-b00b-4b00-811b-b5dd6ed265b3.png">

We obviously don't need to make addons-infotile build, since it's not compatible with the latest full release, but I'm thinking the difference in error might hint at some breaking change?

2022-07-06 11:17 UTC, adrianschmidt commented on packages/commands/src/limeobject/save-object.command.ts
>      Command,
`limepkg-status-flow` builds just fine with `@limetech/lime-web-components@latest` but fails with the following errors with this branch:

<img width="973" alt="A screenshot of four build errors from trying to build limepkg-status-flow with this PR's branch installed" src="https://user-images.githubusercontent.com/154725/177538290-869ca9bf-d02b-49f9-837a-96473c1f1ecd.png">

2022-07-06 11:23 UTC, adrianschmidt commented on packages/commands/src/limeobject/save-object.command.ts
>      Command,
I've got these errors isolated in `limepkg-product-analytics`. It builds fine with `@limetech/lime-web-components@latest`, but gets the following error with this branch:

<img width="952" alt="TypeScript: ./src/components/loader/loader.tsx:20:14 Class 'Loader' incorrectly implements interface 'LimePluginLoader'.Type 'Loader' is missing the following properties from type 'LimePluginLoader': connectedCallback, disconnectedCallback" src="https://user-images.githubusercontent.com/154725/177539171-3d19ef1c-d6a6-48f0-ae44-0c8c9e518cc1.png">

2022-07-06 11:37 UTC, jgroth commented on packages/commands/src/limeobject/save-object.command.ts
>      Command,
I will have a look :slightly_smiling_face:

2022-07-06 12:42 UTC, jgroth commented on packages/commands/src/limeobject/save-object.command.ts
>      Command,
201a529

2022-07-06 12:42 UTC, jgroth commented on packages/commands/src/limeobject/save-object.command.ts
>      Command,
793040a

2022-07-06 13:26 UTC, Befkadu1 commented
Is it only my machine that throws this error ? I had to install `@types/lodash` in each packes
![Screenshot 2022-07-06 at 3 23 39 PM](https://user-images.githubusercontent.com/22968497/177560841-990af2cb-2f69-4583-880d-5540cb91f448.png)

2022-07-06 13:28 UTC, jgroth commented
> Is it only my machine that throws this error ? I had to install `@types/lodash` in each packages ![Screenshot 2022-07-06 at 3 23 39 PM](https://user-images.githubusercontent.com/22968497/177560841-990af2cb-2f69-4583-880d-5540cb91f448.png)

:eyes: 
We don't event seem to be using `lodash` anywhere in this repo :smile:

2022-07-06 13:49 UTC, adrianschmidt commented
> > 👀 We don't event seem to be using `lodash` anywhere in this repo 😄
> 
> May be in the package lock?

`lodash` is used as a sub-dependency of plenty of our dependencies:

<img width="349" alt="A screenshot of the result of running 'npm list lodash' in the branch 'fix-breaking-changes'." src="https://user-images.githubusercontent.com/154725/177565154-f7d0c894-f505-43e1-903b-2c07098a98b0.png">

I don't think you should get that error you are getting because of that though… and I'm not getting it… 🤔

What do you get if you run `npm list -g`?

2022-07-06 13:55 UTC, jgroth commented
> I don't think you should get that error you are getting because of that though… and I'm not getting it… thinking
> 
> What do you get if you run `npm list -g`?

It seems there was a `node_modules` in the parent home folder containing _a lot_ of crap screwing up the build. We removed it and it solved the issue

2022-07-06 14:48 UTC, adrianschmidt commented
> > I don't think you should get that error you are getting because of that though… and I'm not getting it… thinking
> > What do you get if you run `npm list -g`?
> 
> It seems there was a `node_modules` in the parent home folder containing _a lot_ of crap screwing up the build. We removed it and it solved the issue

Hasn't that happened to you before too @Befkadu1? I wonder what's causing that 🤔

2022-07-06 14:50 UTC, adrianschmidt approved these changes
I haven't found any more issues. Should we merge?

2022-07-06 15:02 UTC, Befkadu1 approved these changes
I have tested in the following repos: 
1. limeclient.js
2. lime-crm-components 
3. lime-webclient/frontend/webclient
4. lime-webclient/frontend/admin
5. limepkg-product-analytics 

I could be able to test `SaveLimeObjectCommand`,`translations`

Everything works awesome 🎊

2022-07-06 15:05 UTC, Befkadu1 requested changes
I have 1 error deleting an object. The object is deleted but I can see the error log in the dev tool. I am not sure if related

![Screenshot 2022-07-06 at 5 04 31 PM](https://user-images.githubusercontent.com/22968497/177582602-8c64deeb-1d7a-4415-a064-2f18bdc7d9c5.png)

2022-07-06 15:08 UTC, Befkadu1 commented
> I have 1 error deleting an object. The object is deleted but I can see the error log in the dev tool. I am not sure if related
> 

I can see the error log on production as well so I am approving this

2022-07-06 15:09 UTC, merged