fix: include Stencil in build
Lundalogik/lime-web-components pull request #478
Opened 2022-07-12 08:13 UTC by jgroth

fix Lundalogik/crm-feature#2898

`getElement` from Stencil is used by the decorators and is needed in the build

2022-07-12 14:53 UTC, vicgeralds requested changes
Good to have stencil as a peer dependency. 👍
Not sure why we need this when we didn't before 😄 

The package-lock files are not in sync (means `npm ci` fails) and seem generated by lerna (reformatted with different indentation than when you do `npm install`).

2022-07-12 14:53 UTC, vicgeralds commented on packages/lime-web-components/package.json
> +    "jest-cli": "^27.5.1"
To me it doesn't make any sense to have jest as a peer dependency. Why?

2022-07-13 08:28 UTC, Befkadu1 commented on packages/lime-web-components/package.json
> +    "jest-cli": "^27.5.1"
What is the problem having jest in `devDependencies`?

2022-07-13 08:35 UTC, vicgeralds commented on packages/lime-web-components/package.json
> +    "jest-cli": "^27.5.1"
@Befkadu1 no one said there was a problem having jest in devDependencies. 🙁

2022-07-13 08:37 UTC, vicgeralds commented on packages/lime-web-components/package.json
> +    "jest-cli": "^27.5.1"
He moved them from `peerDependencies`, I can see the comment is confusing without the original context

2022-07-13 13:23 UTC, vicgeralds submitted a review, later dismissed
I updated the package-lock.json files 🙂

2022-07-13 13:28 UTC, jgroth commented
> I updated the package-lock.json files slightly_smiling_face

Great! :slightly_smiling_face:

2022-07-13 13:48 UTC, merged